### PR TITLE
Remove function-calc-no-invalid rule

### LINKED ISSUE #121: Remove function-calc-no-invalid
> What is the problem you're trying to solve?

Suppress `Unknown rule function-calc-no-invalid` errors raised when using `stylelint-config-recommended` (or `stylelint-config-standard`) with Stylelint version 14.

> What solution would you like to see?

Remove `function-calc-no-invalid` from the list of enabled options. Since the option was [removed in release version 14 of Stylelint](https://github.com/stylelint/stylelint/issues/4731), the option should be removed in this project as well.

### PR DESCRIPTION
**Pull request by AndreasNasman**
> Which issue, if any, is this issue related to?

Closes #121

> Is there anything in the PR that needs further explanation?

Only removes a single rule.

### CODE REVIEW

**Comment by AndreasNasman** [comment]
This merge request should be synchronized with [release version 14 of Stylelint](https://github.com/stylelint/stylelint/issues/5205), not sure how this is done in practice. 🙂

**Review by jeddy3 — APPROVED** [review]
Thanks, LGTM!

**Review by ybiquitous — APPROVED** [review]
Thanks. LGTM 👍🏼

**Comment by jeddy3** [comment]
I'll merge when we're ready to release `14.0.0`.

**Comment by jeddy3** [comment]
We can merge this now as another preparation PR is needed for 14.0.0

**Comment by jeddy3** [comment]
Changelog:

> - Removed: `function-calc-no-invalid` rule.

**Pull request merged**
