### PR TITLE
Prepare 5.0.0

### PR DESCRIPTION
**Pull request by jeddy3**
> Which issue, if any, is this issue related to?

None.

### CODE REVIEW

**Review by mattxwang — APPROVED** [review]
Simple enough, LGTM.

**Comment by ybiquitous** [comment]
Like <https://github.com/stylelint/stylelint-config-standard/pull/178>, will you change `index.js` and `package.json` in this PR?

**Comment by jeddy3** [comment]
> Like stylelint/stylelint-config-standard#178, will you change index.js and package.json in this PR?

That's in https://github.com/stylelint/stylelint-config-recommended/pull/97

**Review by ybiquitous — APPROVED** [review]
Sorry, I missed it. LGTM 👍🏼

**Pull request merged**
